{
 "title": "Rails Performance Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Overview",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_metric_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "metric_data",
     "query": "SELECT \"val\" FROM \"metric_data\" WHERE (\"metric_name\" =~ /^[^\\/]+$/) AND $timeFilter GROUP BY \"metric_name\"",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "CPU / Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_metric_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"max\" FROM \"metric_data\" WHERE (\"metric_name\" =~ /CPU\\/.*/) AND $timeFilter GROUP BY \"metric_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_metric_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"max\" FROM \"metric_data\" WHERE (\"metric_name\" =~ /Memory\\/.*/) AND $timeFilter GROUP BY \"metric_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Controllers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_metric_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "metric_data",
     "query": "SELECT \"val\" FROM \"metric_data\" WHERE (\"metric_name\" =~ /^Controller\\/.*/) AND $timeFilter GROUP BY \"metric_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "WebTransactionTotalTime/*",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_metric_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "metric_data",
     "query": "SELECT \"val\" FROM \"metric_data\" WHERE (\"metric_name\" =~ /WebTransactionTotalTime\\/.*/) AND $timeFilter GROUP BY \"metric_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Apdex/*",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_metric_name",
     "groupBy": [
      { "params": [ "metric_name" ], "type": "tag" }
     ],
     "measurement": "metric_data",
     "query": "SELECT \"val\" FROM \"metric_data\" WHERE (\"metric_name\" =~ /Apdex\\/.*/) AND $timeFilter GROUP BY \"metric_name\"",
     "select": [
      [
       { "params": [ "val" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "Apdex/.*" }
     ]
    }
   ]
  },
  {
   "title": "Datastore/operation/*",
   "type": "graph",
   "description": "AKA SQL queries performance metrics",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_metric_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "metric_data",
     "query": "SELECT \"val\" FROM \"metric_data\" WHERE (\"metric_name\" =~ /Datastore\\/operation\\/.*/) AND $timeFilter GROUP BY \"metric_name\"",
     "select": [
      [
       { "params": [ "val" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "metric_name",
       "operator": "=",
       "value": "Datastore/operation/SQLite/find"
      }
     ]
    }
   ]
  },
  {
   "title": "RubyVM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_metric_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"val\" FROM \"metric_data\" WHERE (\"metric_name\" =~ /RubyVM\\/.*/) AND $timeFilter GROUP BY \"metric_name\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}